:examples: ../../examples/onefile


= net


== http_server

Http server for embedding.

It can be used for REST

At the moment, it is a wrapper from fossa  https://github.com/cesanta/fossa[]


    // Http message format
    struct http_message {
      struct ns_str message; // Whole message: request line + headers + body

      struct ns_str proto; // "HTTP/1.1" -- for both request and response
      // HTTP Request line (or HTTP response line)
      struct ns_str method; // "GET"
      struct ns_str uri;    // "/my_file.html"
      // For responses, code and response status message are set
      int resp_code;
      struct ns_str resp_status_msg;

      // *
      // * Query-string part of the URI. For example, for HTTP request
      // *    GET /foo/bar?param1=val1&param2=val2
      // *    |    uri    |     query_string     |
      // *
      // * Note that question mark character doesn't belong neither to the uri,
      // * nor to the query_string
      // *
      struct ns_str query_string;

      // Headers
      struct ns_str header_names[NS_MAX_HTTP_HEADERS];
      struct ns_str header_values[NS_MAX_HTTP_HEADERS];

      // Message body
      struct ns_str body; // Zero-length for requests with no body



.Example
[source,cpp]
----------------
include::{examples}/net/ex_http_server.cpp[]
----------------
